# From here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"
install:
  # Install phase of our CI pipeline
  - pip install .
  - pip install -r build-requirements.txt

script:
  # Run phase of our CI pipeline
  - rr-paper
  # Run unitTests
  - nosetests --nocapture -v tests/test.py --with-coverage --cover-package=rr
  # Generate rst files from docstring
  - sphinx-apidoc -fMeT -o docs/source/api experiment
  # Build documentation
  - sphinx-build docs/source docs/build
  - touch docs/build/.nojekyll
  # Black lint checking
  - black --check experiment/ test/ download_data/
after_success:
  # update coveralls report
  - coveralls

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./docs/build
    on:
        branch: master
        condition: "$TRAVIS_PYTHON_VERSION = 3.8"
  - provider: pypi
      server: https://test.pypi.org/legacy/ # Remove to deployment on pypi.org
      username: "__token__"
      password:
        secure: AgENdGVzdC5weXBpLm9yZwIkNDkzMjE2ZDMtYjlhYy00NTViLTg1MzYtZGU4N2YyNjA0NDY1AAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCE1UhRrnGVriZfsUQEp0YRaWTuAOLsDggCBBsOB-PbMQ
      on:
        tags: true
        condition: "$TRAVIS_PYTHON_VERSION = 3.8"
