# From here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"
install:
  # Install phase of our CI pipeline
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n project python=$TRAVIS_PYTHON_VERSION -c plotly --file requirements.txt
  - conda activate project

script:
  # Run phase of our CI pipeline
  # Run unitTests
  - nosetests --nocapture -v tests/test.py

  # Generate rst files from docstring
  - sphinx-apidoc -fMeT -o docs/source/api scripts
  # Build documentation
  - sphinx-build docs/source docs/build
  - touch docs/build/.nojekyll

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./docs/build
    on:
        branch: master
        condition: $TRAVIS_PYTHON_VERSION = 3.8